services:
  app:
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000
    build: .
    ports:
      - "8000:8000"
    restart: always
    links:
      - postgres_db
    depends_on:
      - postgres_db
    image: stereotekk/veles-auth:app
 

  postgres_db:
    build: ./database
    env_file: ".env.postgres"
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=secret123
       - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    image: stereotekk/veles-auth:postgres_db
  redis_cache:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes



